name = "ParticleTable"
uuid = "f9d7ea0e-6852-4d9a-959f-923059567c30"
version = "0.2.0"
authors = ["kcarloni <kcarloni@g.harvard.edu>"]

[deps]
Corpuscles = "e78a0372-c628-4773-9c8d-eb17d149bf93"
IsotopeTable = "301f09c9-9f3f-4b04-816f-ee47ab44b8cb"
PythonCall = "6099a3de-0909-46bc-b1f4-468b9a2dfc0d"

[compat]
Corpuscles = "2"
IsotopeTable = "0.2"
PythonCall = "0.9"
julia = "1.9"
