name = "ParticleTable"
uuid = "f9d7ea0e-6852-4d9a-959f-923059567c30"
authors = ["kcarloni <kcarloni@g.harvard.edu>"]
version = "0.1.0"

[deps]
Corpuscles = "e78a0372-c628-4773-9c8d-eb17d149bf93"
IsotopeTable = "301f09c9-9f3f-4b04-816f-ee47ab44b8cb"

[weakdeps]
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"

[extensions]
ParticleDecays = "PyCall"